### ISSUE TITLE
A question about isbi 2012 dataset

### ISSUE THREAD

**Issue by lgylylyct** [ZACKLDHGZ/Unet_for_ISBI_2012_data#1]
I visited the website of ISBI2012 (http://brainiac2.mit.edu/isbi_challenge/) and want to download the dataset, but after I registered my account, I did not receive any emails in my mailbox. I tried to change my mailbox and registered again, but it did not work. Could you please tell me how to get the dataset?

**Comment by Void-zack** [comment]
You can download the dataset with this page : [ISBI Challenge Dataset | Kaggle](https://www.kaggle.com/soumikrakshit/isbi-challenge-dataset?select=train-labels.tif)

**Comment by Void-zack** [comment]
You can download the dataset in this page : [ISBI Challenge Dataset | Kaggle](https://www.kaggle.com/soumikrakshit/isbi-challenge-dataset?select=train-labels.tif)

**Comment by HakaseZ** [comment]
> I visited the website of ISBI2012 (http://brainiac2.mit.edu/isbi_challenge/) and want to download the dataset, but after I registered my account, I did not receive any emails in my mailbox. I tried to change my mailbox and registered again, but it did not work. Could you please tell me how to get the dataset?

You can download the dataset in this page : [ISBI Challenge Dataset | Kaggle](https://www.kaggle.com/soumikrakshit/isbi-challenge-dataset?select=train-labels.tif)

**Comment by lgylylyct** [comment]
Thanks a lot !

**Comment by lgylylyct** [comment]
> > I visited the website of ISBI2012 (http://brainiac2.mit.edu/isbi_challenge/) and want to download the dataset, but after I registered my account, I did not receive any emails in my mailbox. I tried to change my mailbox and registered again, but it did not work. Could you please tell me how to get the dataset?
> 
> You can download the dataset in this page : [ISBI Challenge Dataset | Kaggle](https://www.kaggle.com/soumikrakshit/isbi-challenge-dataset?select=train-labels.tif)

Thanks a lot !
